baseurl = "https://adityamenon.co/"
languageCode = "en-us"
title = "Aditya Menon - Full Stack Engineer"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-121966491-1"
# Posts per page
# paginate = 10
pygmentsuseclasses = true

[params]
	author = "Aditya M"
	description = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	# avatar = "img/avatar.png"
	# or use Gravatar by adding an MD5-hash of your email address
	gravatar = "hello@adityamenon.co"
	headerText = "I'm a programming enthusiast. I architect and engineer software systems.<br><br>Building a system from scratch, extending existing systems to make them more capable, or debugging a problematic system - all give me a great deal of joy."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = "code_bg.png"
	copyright = "&copy; Aditya M 2016-2018. All rights reserved."

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = false
		homepage = true
		email = "hello@adityamenon.co"
		# behance = ""
		# bitbucket  =""
		# dribbble = ""
		# facebook = ""
		# flickr = ""
		github = "adityamenon"
		# googleplus = ""
		# instagram = ""
		linkedin = "codeisawesome"
		# pinterest = ""
		# reddit = ""
		# soundcloud = ""
		stackexchange = "https://stackoverflow.com/users/443219/aditya-menon"
		# steam = ""
		# tumblr = ""
		twitter = "codeisawesome"
		# wordpress = ""
		# youtube = ""
